loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 772;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_traget01",
		x:19,
        y:128.4,
        width:171,
        height:36,
        size:11,
		tag:3,
        textAlign:"center"},     
       {compId:"ID_s1_traget02",
		x:19,
        y:176.6,
        width:171,
        height:36,
        size:11,
		tag:2,
        textAlign:"center"},
		{compId:"ID_s1_traget03",
		x:19,
        y:224.8,
        width:171,
        height:36,
        size:11,
		tag:4,
        textAlign:"center"},
	{compId:"ID_s1_traget04",
		x:19,
        y:273,
        width:171,
        height:36,
        size:11,
		tag:5,
        textAlign:"center"},
{compId:"ID_s1_traget05",
		x:19,
        y:321.2,
        width:171,
        height:36,
        size:11,
		tag:1,
        textAlign:"center"},    
       ];
    var dropBox = [{compId:"a1_dt",
        x:219.5,
        y:128.4,
        width:171,
        height:36,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"a2_dt",
        x:219.5,
         y:176.6,
        width:171,
        height:36,
        answer:2,
        textAlign:"center"},
		{compId:"a3_dt",
         x:219.5,
        y:224.8,
        width:171,
        height:36,
        size:11,
        answer:3,
        textAlign:"center"},
        {compId:"a4_dt",
         x:219.5,
        y:273,
        width:171,
        height:36,
        size:11,
        answer:4,
        textAlign:"center"},
		{compId:"a5_dt",
		  x:219.5,
        y:321.2,
        width:171,
        height:36,
        size:11,
        answer:5,
        textAlign:"center"},
       ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [
		{compId:"ID_s1_inst",
        x:30,
        y:1,
        width:375.9,
        height:17,
        size:11,
        textAlign:"left"},
		 {compId:"ID_s1_txt06",
            x:223.5,
            y:106.4,
            width:171,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_s1_txt07",
            x:398.3,
            y:106.4,
            width:194,
            height:17,
            size:11,
            textAlign:"center"},
	
		{compId:"ID_s1_txt01",
			x:398.35,
            y:130.9,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},

       {compId:"ID_s1_txt02",
            x:398.35,
            y:177.1,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
	{compId:"ID_s1_txt03",
			x:398.35,
            y:234.3,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},

       {compId:"ID_s1_txt04",
             x:398.35,
            y:274.5,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
		    {compId:"ID_s1_txt05",
             x:398.35,
            y:330.7,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"bg.png",
							x:203,
							y:98.1, 
							width:539,
							height:269.9,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:568,
        y:377,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
             x:673,
			 y:377,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:19,
        y:105,
        width:170,
        height:98,
        size:11,
        image:"../../../common/images/feedback4.png",
        textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

   var buttons = [{compId:"ID_s2_traget01",
		x:19,
        y:128.4,
        width:171,
        height:36,
        size:11,
		tag:2,
        textAlign:"center"},     
       {compId:"ID_s2_traget02",
		x:19,
        y:176.6,
        width:171,
        height:36,
        size:11,
		tag:4,
        textAlign:"center"},
		{compId:"ID_s2_traget03",
		x:19,
        y:224.8,
        width:171,
        height:36,
        size:11,
		tag:1,
        textAlign:"center"},
	{compId:"ID_s2_traget04",
		x:19,
        y:273,
        width:171,
        height:36,
        size:11,
		tag:3,
        textAlign:"center"},
{compId:"ID_s2_traget05",
		x:19,
        y:321.2,
        width:171,
        height:36,
        size:11,
		tag:5,
        textAlign:"center"},    
       ];
    var dropBox = [{compId:"a1_dt",
        x:219.5,
        y:128.4,
        width:171,
        height:36,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"a2_dt",
        x:219.5,
         y:176.6,
        width:171,
        height:36,
        answer:2,
        textAlign:"center"},
		{compId:"a3_dt",
         x:219.5,
        y:224.8,
        width:171,
        height:36,
        size:11,
        answer:3,
        textAlign:"center"},
        {compId:"a4_dt",
         x:219.5,
        y:273,
        width:171,
        height:36,
        size:11,
        answer:4,
        textAlign:"center"},
		{compId:"a5_dt",
		  x:219.5,
        y:321.2,
        width:171,
        height:36,
        size:11,
        answer:5,
        textAlign:"center"},
       ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [
		{compId:"ID_s2_inst",
        x:30,
        y:1,
        width:375.9,
        height:17,
        size:11,
        textAlign:"left"},
		 {compId:"ID_s2_txt06",
            x:223.5,
            y:106.4,
            width:171,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_s2_txt07",
            x:398.3,
            y:106.4,
            width:194,
            height:17,
            size:11,
            textAlign:"center"},
	
		{compId:"ID_s2_txt01",
			x:398.35,
            y:134.9,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},

       {compId:"ID_s2_txt02",
            x:398.35,
            y:177.1,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
	{compId:"ID_s2_txt03",
			x:398.35,
            y:234.3,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},

       {compId:"ID_s2_txt04",
             x:398.35,
            y:281.5,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
		    {compId:"ID_s2_txt05",
             x:398.35,
            y:325.7,
            width:339,
            height:17,
            size:11,
            textAlign:"left"},
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg.png",
							x:203,
							y:98.1, 
							width:539,
							height:269.9,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s2_CHECK",
        x:568,
        y:377,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s2_RESET",
             x:673,
			 y:377,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:19,
        y:105,
        width:170,
        height:98,
        size:11,
        image:"../../../common/images/feedback4.png",
        textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	
 var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
			
	
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:718}};
	
}



